#Users
User.create(name: 'kelan', password: 'kelan', email: 'kelan@yahoo.com', snowboarder: true)
User.create(name: 'alyssa', password: 'alyssa', email: 'alyssa@yahoo.com', snowboarder: true)

#Mountains 
Mountain.create(title: 'Keystone', address: '100 Dercum Square, Keystone, CO 80435', elevation: '12,408 feet',image:'https://cdn.5280.com/2017/07/Keystone-Abby-Hein.jpg', map:'https://www.keystoneresort.com/-/aemasset/sitecore/keystone/maps/KEY_22-23_Winter-Trail-Map-Web_FINAL.pdf', description:'Keystone Resort is located in Summit County, Colorado, just a short, scenic drive from Denver. Whether youre a family with kids or a kid at heart, this laid-back mountain playground will make you feel right at home. Keystone Resort offers a huge variety of year-round outdoor activities and adventures, comfortable lodging accommodations and award-winning dining, all nestled in the breathtaking Rocky Mountains. With so much to ski and do here, making lasting memories with friends and family comes naturally.')
Mountain.create(title: 'Breckenridge', address: '1599 Ski Hill Rd, Breckenridge, CO 80424', elevation: '12,998 feet',image:'https://dam-assets.vailresorts.com/is/image/vailresorts/Breckenridge-Mountain-Info-Heros-2?wid=1400&fit=vfit,1&resMode=sharp2&w=1400&h=400&hei=1050&dpr=on,2.625', map:'https://www.breckenridge.com/-/media/breckenridge/files/breck-new-trail-map-winter-18_19-converted.ashx', description:'Breckenridge Ski Resort is an alpine ski resort in the western United States, in Breckenridge, Colorado. Just west of the Continental Divide in Summit County, it is perennially one of the most visited ski resorts in the western hemisphere. Breckenridge is owned and operated by Vail Resorts, Inc.')
Mountain.create(title: 'Crested Butte', address: '12 Snowmass Rd, Crested Butte, CO', elevation: '8,909 feet',image:'https://dam-assets.vailresorts.com/is/image/vailresorts/FY20_ctb_sunset?wid=1998&fit=vfit,1&resMode=sharp2&hei=1498&dpr=on,2.625', map:'https://www.skicb.com/-/aemasset/sitecore/crested-butte/maps/20211124_CB_trail_map_002.pdf', description:'Located off the beaten path, Crested Butte is known for some of the best lift-served extreme terrain in the nation. Home to quirky costume events and our friendly vibe, Crested Butte is a place you want to add to your bucket list.')


#Events
Event.create(user_id: 1, mountain_id: 2, name: 'Shred Schoolmarm', time: '12:30')
Event.create(user_id: 2, mountain_id: 1, name: 'Meet me at Peak 6', time: '12:30')
Event.create(user_id: 1, mountain_id: 3, name: 'See ya on Painter Boy',time: '12:30')

#Lifts
Lift.create(title: 'River Run Gondola', mountain_id: 1)
Lift.create(title: 'Outpost Gondola', mountain_id: 1)
Lift.create(title: 'Ruby Express', mountain_id: 1)
Lift.create(title: 'Montezuma Express', mountain_id: 1)
Lift.create(title: 'Peru Express', mountain_id: 1)
Lift.create(title: 'Outback Express', mountain_id: 1)
Lift.create(title: 'Summit Express', mountain_id: 1)
Lift.create(title: 'Wayback', mountain_id: 1)
Lift.create(title: 'Ranger', mountain_id: 1)
Lift.create(title: 'A 51', mountain_id: 1)
Lift.create(title: 'Discovery', mountain_id: 1)

Lift.create(title: 'Breckconnect Gondola', mountain_id: 2)
Lift.create(title: 'Falcon SuperChair', mountain_id: 2)
Lift.create(title: 'Quicksilver SuperChair', mountain_id: 2)
Lift.create(title: 'Colorado SuperChair', mountain_id: 2)
Lift.create(title: 'Independence SuperChair', mountain_id: 2)
Lift.create(title: 'Kensho SuperChair', mountain_id: 2)
Lift.create(title: 'Mercury SuperChair', mountain_id: 2)
Lift.create(title: 'Beaver Run SuperChair', mountain_id: 2)
Lift.create(title: 'Peak 8 SuperConnect', mountain_id: 2)
Lift.create(title: 'Rocky Mountain SuperChair', mountain_id: 2)
Lift.create(title: 'Imperial Express SuperChair', mountain_id: 2)
Lift.create(title: 'Freedom SuperChair', mountain_id: 2)
Lift.create(title: 'Zendo', mountain_id: 2)
Lift.create(title: 'A-lift', mountain_id: 2)
Lift.create(title: 'C-lift', mountain_id: 2)
Lift.create(title: 'E-lift', mountain_id: 2)
Lift.create(title: 'Snowflake', mountain_id: 2)
Lift.create(title: 'Rip Ride', mountain_id: 2)
Lift.create(title: 'Lift-5', mountain_id: 2)
Lift.create(title: 'Lift-6', mountain_id: 2)
Lift.create(title: 'T-Bar', mountain_id: 2)
Lift.create(title: 'Trygve Platter', mountain_id: 2)
Lift.create(title: 'Eldorado Platter', mountain_id: 2)
Lift.create(title: 'Camelback Platter', mountain_id: 2)

Lift.create(title: 'Peachtree', mountain_id: 3)
Lift.create(title: 'Teocalli Lift', mountain_id: 3)
Lift.create(title: 'East River Express', mountain_id: 3)
Lift.create(title: 'Red Lady Express', mountain_id: 3)
Lift.create(title: 'Paradise Express', mountain_id: 3)
Lift.create(title: 'Silver Queen Express', mountain_id: 3)
Lift.create(title: 'West Wall', mountain_id: 3)
Lift.create(title: 'Prospect Lift', mountain_id: 3)
Lift.create(title: 'Painter Boy', mountain_id: 3)
Lift.create(title: 'Gold Link', mountain_id: 3)
Lift.create(title: 'North Face', mountain_id: 3)
Lift.create(title: 'The High Lift', mountain_id: 3)

